#!/bin/sh
# Script para listar todos os testes semânticos organizados por categoria

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         TESTES SEMÂNTICOS - COMPILADOR C.js                   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📊 ESTATÍSTICAS:"
echo "   • Total de testes: 26"
echo "   • Testes de erro: 12"
echo "   • Testes de sucesso: 14"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📁 CATEGORIA: FUNÇÕES (6 testes)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ⚠️  funcaoNaoDeclarada - Chamada de função não declarada"
echo "  ✅ declaracaoFuncaoValida - Declaração válida de função"
echo "  ❌ parametroDuplicado - Parâmetros duplicados"
echo "  ✅ funcaoMultiplosParametros - Função com múltiplos parâmetros"
echo "  ❌ funcaoDuplicada - Função declarada duas vezes"
echo "  ✅ funcaoSemParametros - Função sem parâmetros"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📁 CATEGORIA: ESCOPO (4 testes)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ escopoAninhado - Variáveis em escopos aninhados"
echo "  ❌ variavelForaEscopo - Acesso a variável fora do escopo"
echo "  ✅ variavelLocalSombreiaGlobal - Shadowing de variável"
echo "  ✅ escoposMultiplosNiveis - Múltiplos níveis de escopo"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📁 CATEGORIA: DECLARAÇÕES (3 testes)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ❌ redeclaracaoMesmoEscopo - Redeclaração no mesmo escopo"
echo "  ✅ declaracaoSemInicializacao - Declaração sem inicialização"
echo "  ✅ tiposDiferentesDeclaracao - Diferentes tipos de dados"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📁 CATEGORIA: ATRIBUIÇÕES (3 testes)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ❌ atribuicaoVariavelNaoDeclarada - Atribuição a variável não declarada"
echo "  ✅ atribuicoesCompostasValidas - Atribuições compostas (+=, -=, etc)"
echo "  ❌ atribuicaoCompostaVariavelNaoDeclarada - Atribuição composta inválida"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📁 CATEGORIA: INCREMENTO/DECREMENTO (2 testes)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ incrementoDecrementoValido - Operadores ++ e --"
echo "  ❌ incrementoVariavelNaoDeclarada - Incremento de variável não declarada"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📁 CATEGORIA: TIPOS (1 teste)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ❌ operacoesComTiposDiferentes - Tipos incompatíveis"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📁 CATEGORIA: EXPRESSÕES (1 teste)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ expressaoComplexaValida - Expressões matemáticas complexas"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📁 CATEGORIA: ARRAYS (2 testes)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ arrayDeclaracao - Declaração de arrays"
echo "  ❌ arrayDuplicado - Array com nome duplicado"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📁 CATEGORIA: CONSTANTES (1 teste)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ constDeclaracao - Declaração de constantes"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📁 CATEGORIA: VARIÁVEIS - TESTES ORIGINAIS (3 testes)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ❌ multiplaDeclaracaoInvalida - Múltipla declaração"
echo "  ✅ tabelaSimbolosComplexo - Tabela de símbolos complexa"
echo "  ❌ variavelNaoDeclarada - Variável não declarada"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "LEGENDA:"
echo "  ✅ = Teste de sucesso (deve compilar sem erros)"
echo "  ❌ = Teste de erro (deve produzir erro semântico)"
echo "  ⚠️  = Teste de aviso (produz aviso mas continua)"
echo ""
